// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhostApp) DeepCopyInto(out *GhostApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhostApp.
func (in *GhostApp) DeepCopy() *GhostApp {
	if in == nil {
		return nil
	}
	out := new(GhostApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GhostApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhostAppList) DeepCopyInto(out *GhostAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GhostApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhostAppList.
func (in *GhostAppList) DeepCopy() *GhostAppList {
	if in == nil {
		return nil
	}
	out := new(GhostAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GhostAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhostAppSpec) DeepCopyInto(out *GhostAppSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.Config = in.Config
	in.Persistent.DeepCopyInto(&out.Persistent)
	in.Ingress.DeepCopyInto(&out.Ingress)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhostAppSpec.
func (in *GhostAppSpec) DeepCopy() *GhostAppSpec {
	if in == nil {
		return nil
	}
	out := new(GhostAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhostAppStatus) DeepCopyInto(out *GhostAppStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhostAppStatus.
func (in *GhostAppStatus) DeepCopy() *GhostAppStatus {
	if in == nil {
		return nil
	}
	out := new(GhostAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhostConfigSpec) DeepCopyInto(out *GhostConfigSpec) {
	*out = *in
	out.Database = in.Database
	out.Server = in.Server
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhostConfigSpec.
func (in *GhostConfigSpec) DeepCopy() *GhostConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GhostConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhostDatabaseConnectionSpec) DeepCopyInto(out *GhostDatabaseConnectionSpec) {
	*out = *in
	out.Port = in.Port
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhostDatabaseConnectionSpec.
func (in *GhostDatabaseConnectionSpec) DeepCopy() *GhostDatabaseConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(GhostDatabaseConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhostDatabaseSpec) DeepCopyInto(out *GhostDatabaseSpec) {
	*out = *in
	out.Connection = in.Connection
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhostDatabaseSpec.
func (in *GhostDatabaseSpec) DeepCopy() *GhostDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(GhostDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhostIngressSpec) DeepCopyInto(out *GhostIngressSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.TLS = in.TLS
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhostIngressSpec.
func (in *GhostIngressSpec) DeepCopy() *GhostIngressSpec {
	if in == nil {
		return nil
	}
	out := new(GhostIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhostIngressTLSSpec) DeepCopyInto(out *GhostIngressTLSSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhostIngressTLSSpec.
func (in *GhostIngressTLSSpec) DeepCopy() *GhostIngressTLSSpec {
	if in == nil {
		return nil
	}
	out := new(GhostIngressTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhostPersistentSpec) DeepCopyInto(out *GhostPersistentSpec) {
	*out = *in
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
	out.Size = in.Size.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhostPersistentSpec.
func (in *GhostPersistentSpec) DeepCopy() *GhostPersistentSpec {
	if in == nil {
		return nil
	}
	out := new(GhostPersistentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GhostServerSpec) DeepCopyInto(out *GhostServerSpec) {
	*out = *in
	out.Port = in.Port
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GhostServerSpec.
func (in *GhostServerSpec) DeepCopy() *GhostServerSpec {
	if in == nil {
		return nil
	}
	out := new(GhostServerSpec)
	in.DeepCopyInto(out)
	return out
}
